server:
  port: 8081
#配置mysql数据源
spring:
  datasource:
    url: jdbc:mysql://149.88.76.73:3306/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: root
    password: ~!@root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 149.88.76.73
    port: 6379
    timeout: 3000 #连接超时时间
    password: redis

#配置mybatis加载mapper.xml
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl