server:
  port: 80
#???????
spring:
  datasource:
    url: jdbc:mysql://192.168.1.103/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimeZone=Asia/Shanghai
    username: wiki
    password: wiki
    driver-class-name: com.mysql.cj.jdbc.Driver